[package]
name = "awa-core"
repository.workspace = true
authors.workspace = true
edition.workspace = true
version = "0.1.0"

[dependencies]
thiserror.workspace = true
bitbuffer.workspace = true
num-traits.workspace = true
